.TH terminator "7" "2023-12-08" "baldo/document" "cheatsheet"
.SH NAME
.PP
terminator \- (cheatsheet) 
.SH SYNOPSIS
.PP
terminator
.SH DESCRIPTION

.SS
Group/Broadcast
.EX
  Super+g       : \fBg\fRroup all
  Super+Sh+g    : end group
  Super+t       : group in \fBt\fRab (2 tabs must be present)
  Super+Sh+t    : end group in tab
  Alt+a         : broadcast all
  Alt+g         : broadcast group
  Alt+o         : end broadcast
.EE

.SS
Panneau/Terminal
.EX
   Ctrl\-Sh\-o     : split h\fBo\fRrizontal
   Ctrl\-Sh\-e     : split v\fBe\fRrtical
   Ctrl\-Sh\-w     : close panneau/terminal
   Ctrl\-Alt\-x    : rename panneau
.EE

.SS
Tab
.EX
   Ctrl\-Sh\-t     : new \fBt\fRab
   Ctrl\-Alt\-t    : rename \fBt\fRab
   Dbl\-Click     : rename tab
   Ctrl\-Sh\-q     : \fBq\fRuit all
.EE

.SS
Navigation
.EX
   Alt\-→↓        : move to panel
   Ctrl\-Sh\-n     : move to \fBn\fRext panel
   Ctrl\-Sh\-p     : move to \fBp\fRrev. panel
   Ctrl\-Tab      : move to next panel
   Ctrl\-Sh\-Tab   : move to previous panel
   Ctrl\-PgDown   : move to next tab
   Ctrl\-PgUp     : move to previous tab
.EE

.SS
Divers
.EX
   Ctrl+sh+s    : show/hide scrollbar
   Ctrl+ +      : font size ++
   Ctrl+ \-      : font size \-\-
   Ctrl+Alt+w   : rename window
   Ctrl+Sh+i    : new term\fBi\fRnator
.EE
